version: "3.8"
services:
  postgres14:
    image: postgres:14.5-alpine
    container_name: postgres14
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
